<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="process" nsURI="http://inria.fuchsia.gag.gagmt/process/" nsPrefix="process">
    <eClassifiers xsi:type="ecore:EClass" name="Task">
      <eOperations name="applyRule">
        <eParameters name="rule" eType="/1/Rule"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_open">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="appliedRule">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associated_to" eType="/1/Service"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sub_task" upperBound="-1" eType="/0/Task" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Configuration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="/0/Task"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="consistent_to" lowerBound="1" eType="/1/GAG"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="specification" nsURI="http://inria.fuchsia.gag.gagmt/specification/" nsPrefix="specification">
    <eClassifiers xsi:type="ecore:EClass" name="GAG">
      <eOperations name="addRule">
        <eParameters name="rule" eType="/1/Rule"/>
      </eOperations>
      <eOperations name="removeRule">
        <eParameters name="rule" eType="/1/Rule"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1" upperBound="-1" eType="/1/Rule" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="/1/Attribute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="/1/Attribute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Guard">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="classPath" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rule">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left_hand_side" lowerBound="1" eType="/1/Service"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" transient="true">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right_hand_side_service" upperBound="-1" eType="/1/Service"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="/1/Guard"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
