/**
 * generated by Xtext 2.14.0
 */
package fr.inria.gag.specification.xtext;

import fr.inria.gag.specification.xtext.GagStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GagStandaloneSetup extends GagStandaloneSetupGenerated {
  public static void doSetup() {
    new GagStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
