/**
 * generated by Xtext 2.14.0
 */
package fr.inria.gag.specification.xtext.scoping;

import fr.inria.gag.specification.xtext.scoping.AbstractGagScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GagScopeProvider extends AbstractGagScopeProvider {
}
