/*
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.gagdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GagDslStandaloneSetup extends GagDslStandaloneSetupGenerated {

	def static void doSetup() {
		new GagDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
