/*
 * generated by Xtext 2.14.0
 */
package fr.inria.gag.specification.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGagScopeProvider extends DelegatingScopeProvider {
}
