/*
 * generated by Xtext 2.14.0
 */
package fr.inria.gag.specification.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.inria.gag.specification.xtext.ide.contentassist.antlr.internal.InternalGagParser;
import fr.inria.gag.specification.xtext.services.GagGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GagParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GagGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GagGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getRightPartExpressionAccess().getAlternatives(), "rule__RightPartExpression__Alternatives");
			builder.put(grammarAccess.getGAGAccess().getGroup(), "rule__GAG__Group__0");
			builder.put(grammarAccess.getGAGAccess().getGroup_3(), "rule__GAG__Group_3__0");
			builder.put(grammarAccess.getGAGAccess().getGroup_3_2(), "rule__GAG__Group_3_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup(), "rule__Service__Group__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_2(), "rule__Service__Group_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_2_2(), "rule__Service__Group_2_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3(), "rule__Service__Group_3__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_2(), "rule__Service__Group_3_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_7(), "rule__Service__Group_7__0");
			builder.put(grammarAccess.getDecompositionRuleAccess().getGroup(), "rule__DecompositionRule__Group__0");
			builder.put(grammarAccess.getDecompositionRuleAccess().getGroup_3(), "rule__DecompositionRule__Group_3__0");
			builder.put(grammarAccess.getDecompositionRuleAccess().getGroup_3_3(), "rule__DecompositionRule__Group_3_3__0");
			builder.put(grammarAccess.getDecompositionRuleAccess().getGroup_4(), "rule__DecompositionRule__Group_4__0");
			builder.put(grammarAccess.getDecompositionRuleAccess().getGroup_5(), "rule__DecompositionRule__Group_5__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getGuardAccess().getGroup(), "rule__Guard__Group__0");
			builder.put(grammarAccess.getSemanticRuleAccess().getGroup(), "rule__SemanticRule__Group__0");
			builder.put(grammarAccess.getSemanticRuleAccess().getGroup_2(), "rule__SemanticRule__Group_2__0");
			builder.put(grammarAccess.getSemanticRuleAccess().getGroup_2_3(), "rule__SemanticRule__Group_2_3__0");
			builder.put(grammarAccess.getSemanticRuleAccess().getGroup_3(), "rule__SemanticRule__Group_3__0");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getGroup(), "rule__FunctionDeclaration__Group__0");
			builder.put(grammarAccess.getEquationAccess().getGroup(), "rule__Equation__Group__0");
			builder.put(grammarAccess.getIdExpressionAccess().getGroup(), "rule__IdExpression__Group__0");
			builder.put(grammarAccess.getFunctionExpressionAccess().getGroup(), "rule__FunctionExpression__Group__0");
			builder.put(grammarAccess.getFunctionExpressionAccess().getGroup_2(), "rule__FunctionExpression__Group_2__0");
			builder.put(grammarAccess.getFunctionExpressionAccess().getGroup_2_1(), "rule__FunctionExpression__Group_2_1__0");
			builder.put(grammarAccess.getGAGAccess().getNameAssignment_2(), "rule__GAG__NameAssignment_2");
			builder.put(grammarAccess.getGAGAccess().getServicesAssignment_3_1(), "rule__GAG__ServicesAssignment_3_1");
			builder.put(grammarAccess.getGAGAccess().getServicesAssignment_3_2_1(), "rule__GAG__ServicesAssignment_3_2_1");
			builder.put(grammarAccess.getServiceAccess().getIsAxiomAssignment_0(), "rule__Service__IsAxiomAssignment_0");
			builder.put(grammarAccess.getServiceAccess().getNameAssignment_1(), "rule__Service__NameAssignment_1");
			builder.put(grammarAccess.getServiceAccess().getInputParametersAssignment_2_1(), "rule__Service__InputParametersAssignment_2_1");
			builder.put(grammarAccess.getServiceAccess().getInputParametersAssignment_2_2_1(), "rule__Service__InputParametersAssignment_2_2_1");
			builder.put(grammarAccess.getServiceAccess().getOutputParametersAssignment_3_1(), "rule__Service__OutputParametersAssignment_3_1");
			builder.put(grammarAccess.getServiceAccess().getOutputParametersAssignment_3_2_1(), "rule__Service__OutputParametersAssignment_3_2_1");
			builder.put(grammarAccess.getServiceAccess().getRulesAssignment_6(), "rule__Service__RulesAssignment_6");
			builder.put(grammarAccess.getServiceAccess().getRulesAssignment_7_1(), "rule__Service__RulesAssignment_7_1");
			builder.put(grammarAccess.getDecompositionRuleAccess().getNameAssignment_1(), "rule__DecompositionRule__NameAssignment_1");
			builder.put(grammarAccess.getDecompositionRuleAccess().getSubServicesAssignment_3_2(), "rule__DecompositionRule__SubServicesAssignment_3_2");
			builder.put(grammarAccess.getDecompositionRuleAccess().getSubServicesAssignment_3_3_1(), "rule__DecompositionRule__SubServicesAssignment_3_3_1");
			builder.put(grammarAccess.getDecompositionRuleAccess().getGuardAssignment_4_2(), "rule__DecompositionRule__GuardAssignment_4_2");
			builder.put(grammarAccess.getDecompositionRuleAccess().getSemanticAssignment_5_2(), "rule__DecompositionRule__SemanticAssignment_5_2");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_1(), "rule__Parameter__NameAssignment_1");
			builder.put(grammarAccess.getGuardAccess().getLocationAssignment_3(), "rule__Guard__LocationAssignment_3");
			builder.put(grammarAccess.getGuardAccess().getMethodAssignment_7(), "rule__Guard__MethodAssignment_7");
			builder.put(grammarAccess.getSemanticRuleAccess().getFunctionDeclarationAssignment_2_2(), "rule__SemanticRule__FunctionDeclarationAssignment_2_2");
			builder.put(grammarAccess.getSemanticRuleAccess().getFunctionDeclarationAssignment_2_3_1(), "rule__SemanticRule__FunctionDeclarationAssignment_2_3_1");
			builder.put(grammarAccess.getSemanticRuleAccess().getEquationsAssignment_3_2(), "rule__SemanticRule__EquationsAssignment_3_2");
			builder.put(grammarAccess.getSemanticRuleAccess().getEquationsAssignment_3_3(), "rule__SemanticRule__EquationsAssignment_3_3");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getNameAssignment_0(), "rule__FunctionDeclaration__NameAssignment_0");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getLocationAssignment_4(), "rule__FunctionDeclaration__LocationAssignment_4");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getMethodAssignment_8(), "rule__FunctionDeclaration__MethodAssignment_8");
			builder.put(grammarAccess.getEquationAccess().getLeftpartAssignment_0(), "rule__Equation__LeftpartAssignment_0");
			builder.put(grammarAccess.getEquationAccess().getRightpartAssignment_2(), "rule__Equation__RightpartAssignment_2");
			builder.put(grammarAccess.getLocalDataAccess().getNameAssignment(), "rule__LocalData__NameAssignment");
			builder.put(grammarAccess.getIdExpressionAccess().getServiceNameAssignment_0(), "rule__IdExpression__ServiceNameAssignment_0");
			builder.put(grammarAccess.getIdExpressionAccess().getParameterNameAssignment_2(), "rule__IdExpression__ParameterNameAssignment_2");
			builder.put(grammarAccess.getFunctionExpressionAccess().getFunctionAssignment_0(), "rule__FunctionExpression__FunctionAssignment_0");
			builder.put(grammarAccess.getFunctionExpressionAccess().getExpressionsAssignment_2_0(), "rule__FunctionExpression__ExpressionsAssignment_2_0");
			builder.put(grammarAccess.getFunctionExpressionAccess().getExpressionsAssignment_2_1_1(), "rule__FunctionExpression__ExpressionsAssignment_2_1_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GagGrammarAccess grammarAccess;

	@Override
	protected InternalGagParser createParser() {
		InternalGagParser result = new InternalGagParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GagGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GagGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
