/*
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGagScopeProvider extends DelegatingScopeProvider {
}
