/*
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.gagdsl.ui;

import com.google.inject.Injector;
import inria.fuchsia.gag.gagdsl.ui.internal.GagdslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GagDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(GagdslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		GagdslActivator activator = GagdslActivator.getInstance();
		return activator != null ? activator.getInjector(GagdslActivator.INRIA_FUCHSIA_GAG_GAGDSL_GAGDSL) : null;
	}

}
