/*
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.gagdsl.serializer;

import com.google.inject.Inject;
import inria.fuchsia.gag.gagdsl.services.GagDslGrammarAccess;
import inria.fuchsia.gag.xdsml.gag.process.Configuration;
import inria.fuchsia.gag.xdsml.gag.process.ProcessPackage;
import inria.fuchsia.gag.xdsml.gag.process.Task;
import inria.fuchsia.gag.xdsml.gag.specification.GAG;
import inria.fuchsia.gag.xdsml.gag.specification.Guard;
import inria.fuchsia.gag.xdsml.gag.specification.Rule;
import inria.fuchsia.gag.xdsml.gag.specification.Service;
import inria.fuchsia.gag.xdsml.gag.specification.SpecificationPackage;
import inria.fuchsia.gag.xdsml.gag.specification.Value;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class GagDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private GagDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ProcessPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ProcessPackage.CONFIGURATION:
				sequence_Configuration(context, (Configuration) semanticObject); 
				return; 
			case ProcessPackage.TASK:
				sequence_Task(context, (Task) semanticObject); 
				return; 
			}
		else if (epackage == SpecificationPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SpecificationPackage.GAG:
				sequence_GAG(context, (GAG) semanticObject); 
				return; 
			case SpecificationPackage.GUARD:
				sequence_Guard(context, (Guard) semanticObject); 
				return; 
			case SpecificationPackage.RULE:
				sequence_Rule(context, (Rule) semanticObject); 
				return; 
			case SpecificationPackage.SERVICE:
				sequence_Service(context, (Service) semanticObject); 
				return; 
			case SpecificationPackage.VALUE:
				sequence_Value(context, (Value) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Configuration returns Configuration
	 *
	 * Constraint:
	 *     (name=EString root=[Task|EString] consistent_to=[GAG|EString])
	 */
	protected void sequence_Configuration(ISerializationContext context, Configuration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ProcessPackage.Literals.CONFIGURATION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProcessPackage.Literals.CONFIGURATION__NAME));
			if (transientValues.isValueTransient(semanticObject, ProcessPackage.Literals.CONFIGURATION__ROOT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProcessPackage.Literals.CONFIGURATION__ROOT));
			if (transientValues.isValueTransient(semanticObject, ProcessPackage.Literals.CONFIGURATION__CONSISTENT_TO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ProcessPackage.Literals.CONFIGURATION__CONSISTENT_TO));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConfigurationAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getConfigurationAccess().getRootTaskEStringParserRuleCall_4_0_1(), semanticObject.eGet(ProcessPackage.Literals.CONFIGURATION__ROOT, false));
		feeder.accept(grammarAccess.getConfigurationAccess().getConsistent_toGAGEStringParserRuleCall_6_0_1(), semanticObject.eGet(ProcessPackage.Literals.CONFIGURATION__CONSISTENT_TO, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     GAG returns GAG
	 *
	 * Constraint:
	 *     (name=EString rule+=Rule rule+=Rule*)
	 */
	protected void sequence_GAG(ISerializationContext context, GAG semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Guard returns Guard
	 *
	 * Constraint:
	 *     classPath=EString
	 */
	protected void sequence_Guard(ISerializationContext context, Guard semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SpecificationPackage.Literals.GUARD__CLASS_PATH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SpecificationPackage.Literals.GUARD__CLASS_PATH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getGuardAccess().getClassPathEStringParserRuleCall_3_0(), semanticObject.getClassPath());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Rule returns Rule
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         left_hand_side=[Service|EString] 
	 *         (right_hand_side_service+=[Service|EString] right_hand_side_service+=[Service|EString]*)? 
	 *         guard=[Guard|EString]?
	 *     )
	 */
	protected void sequence_Rule(ISerializationContext context, Rule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Service returns Service
	 *
	 * Constraint:
	 *     (name=EString (input+=Value input+=Value*)? (output+=Value output+=Value*)?)
	 */
	protected void sequence_Service(ISerializationContext context, Service semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Task returns Task
	 *
	 * Constraint:
	 *     (
	 *         is_open?='is_open'? 
	 *         name=EString 
	 *         id=ELong 
	 *         appliedRule=EString? 
	 *         instance_of=[Service|EString]? 
	 *         (sub_task+=Task sub_task+=Task*)?
	 *     )
	 */
	protected void sequence_Task(ISerializationContext context, Task semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Value returns Value
	 *
	 * Constraint:
	 *     (defined?='defined' name=EString value=EJavaObject? (sub_value+=Value sub_value+=Value*)?)
	 */
	protected void sequence_Value(ISerializationContext context, Value semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
