/**
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.gagdsl;

import inria.fuchsia.gag.gagdsl.AbstractGagDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GagDslRuntimeModule extends AbstractGagDslRuntimeModule {
}
