/*
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGagValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://inria.fuchsia.gag.gag/process/"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://inria.fuchsia.gag.gag/specification/"));
		return result;
	}
}
