/*
 * generated by Xtext 2.14.0
 */
package fr.inria.gag.specification.xtext.tests

import com.google.inject.Inject
import fr.inria.gag.specification.model.specification.GAG
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(GagInjectorProvider)
class GagParsingTest {
	@Inject
	ParseHelper<GAG> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
