/**
 * generated by Xtext 2.14.0
 */
package fr.inria.gag.specification.xtext.ide;

import fr.inria.gag.specification.xtext.ide.AbstractGagIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GagIdeModule extends AbstractGagIdeModule {
}
