/**
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.gagdsl.ui.contentassist;

import inria.fuchsia.gag.gagdsl.ui.contentassist.AbstractGagDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GagDslProposalProvider extends AbstractGagDslProposalProvider {
}
