/**
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.xtext.validation;

import inria.fuchsia.gag.xtext.validation.AbstractGagValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GagValidator extends AbstractGagValidator {
}
