/*
 * generated by Xtext 2.14.0
 */
package fr.inria.gag.specification.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GagStandaloneSetup extends GagStandaloneSetupGenerated {

	def static void doSetup() {
		new GagStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
