/**
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import inria.fuchsia.gag.xtext.GagRuntimeModule;
import inria.fuchsia.gag.xtext.GagStandaloneSetup;
import inria.fuchsia.gag.xtext.ide.GagIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GagIdeSetup extends GagStandaloneSetup {
  @Override
  public Injector createInjector() {
    GagRuntimeModule _gagRuntimeModule = new GagRuntimeModule();
    GagIdeModule _gagIdeModule = new GagIdeModule();
    return Guice.createInjector(Modules2.mixin(_gagRuntimeModule, _gagIdeModule));
  }
}
