/**
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.xtext;

import inria.fuchsia.gag.xtext.AbstractGagRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GagRuntimeModule extends AbstractGagRuntimeModule {
}
