/*
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.gagdsl.parser.antlr;

import com.google.inject.Inject;
import inria.fuchsia.gag.gagdsl.parser.antlr.internal.InternalGagDslParser;
import inria.fuchsia.gag.gagdsl.services.GagDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GagDslParser extends AbstractAntlrParser {

	@Inject
	private GagDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGagDslParser createParser(XtextTokenStream stream) {
		return new InternalGagDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Configuration";
	}

	public GagDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GagDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
