/**
 * generated by Xtext 2.14.0
 */
package inria.fuchsia.gag.gagdsl.ide;

import inria.fuchsia.gag.gagdsl.ide.AbstractGagDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GagDslIdeModule extends AbstractGagDslIdeModule {
}
