<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="configuration" nsURI="http://www.inria.fr/gag/configuration"
    nsPrefix="configuration">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="specification" value="../../fr.inria.gag.specification.model/model/specification.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="../../fr.inria.gag.specification.model/model/specification.ecore#//RuntimeData">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//Task"
        containment="true">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pendingLocalComputations"
        upperBound="-1" eType="#//PendingLocalFunctionComputation" containment="true">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.gag.specification.model/model/specification.ecore#//Parameter">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTasks" upperBound="-1"
        eType="#//Task" containment="true">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Data" containment="true">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Data" containment="true">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appliedRule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOpen" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="ecore:EClass ../../fr.inria.gag.specification.model/model/specification.ecore#//Service">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PendingLocalFunctionComputation">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functiondeclaration" lowerBound="1"
        eType="ecore:EClass ../../fr.inria.gag.specification.model/model/specification.ecore#//FunctionDeclaration">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualParameters" upperBound="-1"
        eType="#//Data">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataToCompute" lowerBound="1"
        eType="#//Data">
      <eAnnotations source="aspect"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
